print("     *    "*2)
print("    * *   "*2)
print("   *   *  "*2)
print("  *     * "*2)
print(" **     **"*2)
print("   *   *  "*2)
print("   *   *  "*2)
print("   *****  "*2)
print(" ")
print("      *","\n    *  *","\n   *    *","\n  *      *","\n *        *","\n***      ***","\n  *     *","\n  *     *","\n  *     *","\n  *     *","\n  *******")
print(" ")
print("   *****  "*2)
print("   *   *  "*2)
print("   *   *  "*2)
print(" **     **"*2)
print("  *     * "*2)
print("   *   *  "*2)
print("    * *   "*2)
print("     *    "*2)


